name: CI

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"
          cache-dependency-path: package-lock.json
      - run: npm ci
      - run: mkdir -p src/configs
      - run: 'echo "$FIREBASE_JSON" > src/configs/firebase.json'
        shell: bash
        env:
          FIREBASE_JSON: ${{ secrets.FIREBASE_JSON }}
      - run: npm run check
      - run: npx playwright install
      - run: npm run test
